# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e42c25d0f6caf723f68e7469d0b44f0ad7df2b76af9621cab8fd25bcde305fab697c1a75821de4568f77e52a647aaca4eeee27706ff9751c9b28eebfe9920143

test:
  secret_key_base: b221ebe637fb0eb5f8e62ab071ea2e1f8add689deed0bbd6181230084b9c5ee254e97327d92304305bd1918527ba4a869448d2d140560efa131798b43c00da05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
